#ifndef _MINIHV_STATUS
#define _MINIHV_STATUS

#define STATUS_SUCCESS_BIT
#define STATUS_ERROR_BITS           0xC0000000  // bits 30:31  set - (iff bit 31 set -> NT_SUCCESS(x) will result in fail)
#define STATUS_INFORMATIONAL_BITS   0x60000000  // bits 27:28  set
#define STATUS_WARNING_BITS         0xA0000000  // bits 31, 29 set

#define STATUS_ACPI                 0x8000000
#define STATUS_VMX                  0x4000000
#define STATUS_CPU                  0x2000000
#define STATUS_MSR                  0x1000000

/// VMX Status
#define STATUS_VMX_NOT_SUPPORTED                    ((NTSTATUS)STATUS_ERROR_BITS|STATUS_VMX|0x0001L)
#define STATUS_VMX_FAILED_WITH_ERR_CODE             ((NTSTATUS)STATUS_ERROR_BITS|STATUS_VMX|0x0002L)
#define STATUS_VMX_FAILED_WITHOUT_ERR_CODE          ((NTSTATUS)STATUS_ERROR_BITS|STATUS_VMX|0x0003L)
#define STATUS_VMX_EPT_PAGE_WALK_FOUR_NOT_SUPP      ((NTSTATUS)STATUS_ERROR_BITS|STATUS_VMX|0x0004L)
#define STATUS_VMX_LAUNCH_FAILED                    ((NTSTATUS)STATUS_ERROR_BITS|STATUS_VMX|0x0005L)

/// CPU Status
#define STATUS_NOT_GENUINE_INTEL                    ((NTSTATUS)STATUS_ERROR_BITS|STATUS_CPU|0x0001L)

/// MSR Status
#define STATUS_MSR_FEATURE_CONTROL_REQ_BITS_FAIL    ((NTSTATUS)STATUS_ERROR_BITS|STATUS_MSR|0x0001L)

#endif // _MINIHV_STATUS
